// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwKN_QkK1l_WzYXVvUqyvKW2TNNyGVVk',
    appId: '1:893721094149:web:440a6902c2495b6a9b546c',
    messagingSenderId: '893721094149',
    projectId: 'conspirapcy-8d635',
    authDomain: 'conspirapcy-8d635.firebaseapp.com',
    storageBucket: 'conspirapcy-8d635.appspot.com',
    measurementId: 'G-ZMSXBWQQN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWJZBc6WHH4lu1ZsE8mcKoYf08f9LadM',
    appId: '1:893721094149:android:c9f82d4d10db78379b546c',
    messagingSenderId: '893721094149',
    projectId: 'conspirapcy-8d635',
    storageBucket: 'conspirapcy-8d635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNcMOhQHdqPv-yumEQ635Yh43TCal-sY',
    appId: '1:893721094149:ios:b9e04baf6930c6f29b546c',
    messagingSenderId: '893721094149',
    projectId: 'conspirapcy-8d635',
    storageBucket: 'conspirapcy-8d635.appspot.com',
    iosClientId: '893721094149-7uo2pbps85tjckrbsct1jqo2jud0di41.apps.googleusercontent.com',
    iosBundleId: 'com.example.conspirapcy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNcMOhQHdqPv-yumEQ635Yh43TCal-sY',
    appId: '1:893721094149:ios:03886d21077d98629b546c',
    messagingSenderId: '893721094149',
    projectId: 'conspirapcy-8d635',
    storageBucket: 'conspirapcy-8d635.appspot.com',
    iosClientId: '893721094149-l8hcg2s0614tnjf6241j1hilglkdjoqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.conspirapcy.RunnerTests',
  );
}
